version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./:/app
    restart: unless-stopped
